### ISSUE TITLE
执行最后一步时报错，求教

### ISSUE THREAD

**Issue by asd651257822** [mikumifa/QChatGPT-Docker-Installer#12]
root@ezucjfuyjd5ywtp5:~/QChatGPT-Docker-Installer# docker compose run -itd setup
[+] Building 6.4s (6/6) FINISHED
 => [internal] load build definition from _setup.Dockerfile                                      0.0s
 => => transferring dockerfile: 798B                                                             0.0s
 => [internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                               0.8s
 => [1/3] FROM docker.io/library/python:3.9-slim@sha256:3bab254e90bb0986ead59a3d415e719439e629d  0.0s
 => CACHED [2/3] WORKDIR /bot                                                                    0.0s
 => ERROR [3/3] RUN sed -i "s/deb.debian.org/mirrors.tencent.com/g" /etc/apt/sources.list    &&  5.6s
------
 > [3/3] RUN sed -i "s/deb.debian.org/mirrors.tencent.com/g" /etc/apt/sources.list    && apt-get clean     && apt-get update     && apt install unzip build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget git libbz2-dev -y     && python -m pip install --upgrade pip -i http://pypi.douban.com/simple --trusted-host pypi.douban.com    && pip install colorlog func-timeout openai websockets yiri-mirai -i https://pypi.tuna.tsinghua.edu.cn/simple     && pip install websockets --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple:
#0 0.739 Get:1 http://mirrors.tencent.com/debian bullseye InRelease [116 kB]
#0 0.759 Get:2 http://mirrors.tencent.com/debian-security bullseye-security InRelease [48.4 kB]
#0 0.760 Get:3 http://mirrors.tencent.com/debian bullseye-updates InRelease [44.1 kB]
#0 0.952 Get:4 http://mirrors.tencent.com/debian bullseye/main amd64 Packages [8183 kB]
#0 1.594 Get:5 http://mirrors.tencent.com/debian-security bullseye-security/main amd64 Packages [222 kB]
#0 4.201 Reading package lists...
#0 5.483 E: Release file for http://mirrors.tencent.com/debian/dists/bullseye-updates/InRelease is expired (invalid since 1h 46min 5s). Updates for this repository will not be applied.
------
failed to solve: process "/bin/sh -c sed -i \"s/deb.debian.org/mirrors.tencent.com/g\" /etc/apt/sources.list    && apt-get clean     && apt-get update     && apt install unzip build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget git libbz2-dev -y     && python -m pip install --upgrade pip -i http://pypi.douban.com/simple --trusted-host pypi.douban.com    && pip install colorlog func-timeout openai websockets yiri-mirai -i https://pypi.tuna.tsinghua.edu.cn/simple     && pip install websockets --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple" did not complete successfully: exit code: 100

**Comment by NothAmor** [comment]
这个问题我也遇到了, 找到`_setup.Dockerfile`文件中的`RUN sed -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list\`, 将`mirrors.tencent.com`修改成`mirrors.aliyun.com`试试

**Comment by cherrieszzz** [comment]
将mirrors.tencent.com修改成mirrors.aliyun.com还是会报相同的错误

**Comment by mikumifa** [comment]
试着换其他的源，我刚刚测试没啥问题
