### ISSUE TITLE
执行docker-compose run --rm mirai 报错

### ISSUE THREAD

**Issue by d4renk** [mikumifa/QChatGPT-Docker-Installer#13]
**~/dockers/QChatGPT-Docker-Installer main ❯ docker-compose run --rm mirai                                                                                                                                        
Creating qchatgpt-docker-installer_mirai_run ... done
Error: Unable to access jarfile mcl.jar
ERROR: 1
月初时候搭建过一次，但升级后怎么也不响应
打算重装但似乎少了什么文件**

**Comment by mikumifa** [comment]
检查mirai文件夹里面文件是否正确，有问题就把镜像删了了重新生成镜像，我前天重新装了，没有问题

**Comment by posssss** [comment]
我也遇到了这个问题~~~

**Comment by mikumifa** [comment]
loadFile.sh下载的版本太老了，可以直接去作者那里下载最新的版本

> > 检查mirai文件夹里面文件是否正确，有问题就把镜像删了了重新生成镜像，我前天重新装了，没有问题
> 
> 似乎少了mcl.jar 跟删除的sh有关[loadFile.sh](https://github.com/mikumifa/QChatGPT-Docker-Installer/commit/2e33e282bf69a71f4596b0afd45549c8bbda94d0)
> 
> 我重新执行了[loadFile.sh](https://github.com/mikumifa/QChatGPT-Docker-Installer/commit/2e33e282bf69a71f4596b0afd45549c8bbda94d0)
> 
> 再执行docker compose run --rm mirai ，然后报错，和升级产生的报错一样
> 
> 2023-02-13 07:49:57 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off. 2023-02-13 07:49:57 I/MahKtorAdapter[http]: Application started in 0.277 seconds. 2023-02-13 07:49:57 E/mirai-api-http: kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine is cancelling; job=LazyStandaloneCoroutine{Cancelling}@734ce281 kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine is cancelling; job=LazyStandaloneCoroutine{Cancelling}@734ce281 Caused by: java.net.BindException: Address in use at java.base/sun.nio.ch.Net.bind0(Native Method) at java.base/sun.nio.ch.Net.bind(Net.java:552) at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:336) at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.ConnectUtilsJvmKt.bind(ConnectUtilsJvm.kt:35) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:45) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:29) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind$default(TcpSocketBuilder.kt:25) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:48) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> 
> 2023-02-13 07:49:57 E/MahKtorAdapter[http]: java.net.BindException: Address in use java.net.BindException: Address in use at java.base/sun.nio.ch.Net.bind0(Native Method) at java.base/sun.nio.ch.Net.bind(Net.java:552) at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:336) at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.ConnectUtilsJvmKt.bind(ConnectUtilsJvm.kt:35) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:45) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:29) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind$default(TcpSocketBuilder.kt:25) at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:48) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> 
> 2023-02-13 07:49:57 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8 2023-02-13 07:49:57 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用 2023-02-13 07:49:57 I/main: 1 plugin(s) enabled. 2023-02-13 07:49:57 I/main: mirai-console started successfully.

**Comment by mikumifa** [comment]
`#!/bin/bash
git clone https://github.com/RockChinQ/QChatGPT
mv QChatGPT bot
wget https://github.com/iTXTech/mirai-console-loader/releases/download/v2.1.2/mcl-2.1.2.zip
unzip mcl-2.1.2.zip
mv mcl-2.1.2 mirai
rm -rf mcl-2.1.2.zip
`
大概写了一下

**Comment by mikumifa** [comment]
给一下运行loadFile.sh的报错，应该是你没有下载[mcl](https://github.com/iTXTech/mirai-console-loader/releases/download/v2.1.2/mcl-2.1.2.zip)

**Comment by mikumifa** [comment]
根目录应该是这样
```
├── bot
│   ├── config-template.py
│   ├── LICENSE
│   ├── main.py
│   ├── pkg
│   ├── README.md
│   ├── requirements.txt
│   ├── res
│   ├── sensitive.json
│   └── tests
├── docker-compose.yaml
├── mirai
│   ├── LICENSE
│   ├── mcl
│   ├── mcl.cmd
│   ├── mcl.jar
│   └── README.md
├── _mirai.Dockerfile
└── _setup.Dockerfile
```

**Comment by mikumifa** [comment]
修改了loadfile.sh，现在应该没问题了

**Comment by mikumifa** [comment]
> > 修改了loadfile.sh，现在应该没问题了
> 
> 执行docker-compose run setup 报错， 另外docker-compose run -itd setup有语法错误 没指定shell 正确的语法应该是docker-compose run setup -itd /bin/sh
> 
> [2023-02-13 16:45:40.700] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
> 仅 HTTP 轮询与正向 WebSocket 可用。
> 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
> 在命令行键入：
>     pip install uvicorn
> 或者
>     pip install hypercorn
> 2023-02-13 16:45:50 - ERROR
> ERROR:
> [2023-02-13 16:45:50.717] base.py (43) - [ERROR] :
> ERROR: 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
> [2023-02-13 16:45:50.720] main.py (183) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
>     await protocol.handshake(
>   File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
>     raise InvalidStatusCode(status_code, response_headers)
> websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 680, in __await_impl__
>     await protocol.wait_closed()
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
>     return fut.result()
> asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.9/threading.py", line 917, in run
>     self._target(*self._args, **self._kwargs)
>   File "/bot/main.py", line 186, in run_bot_wrapper
>     raise e
>   File "/bot/main.py", line 148, in run_bot_wrapper
>     qqbot.bot.run()
>   File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
>     MiraiRunner(self).run(host, port, asgi_server, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
>     asyncio.run(self._run())
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
>     await self.startup()
>   File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
>     await asyncio.gather(*coros)
>   File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
>     await self._adapter.login(self.qq)
>   File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
>     return await func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
>     self.connection = await connect(self.host_name, extra_headers=headers)
>   File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
>     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
>   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
>     raise exceptions.TimeoutError() from exc
> asyncio.exceptions.TimeoutError
> ERROR: 1

这个可以去原项目看看，应该是配置文件问题
