### ISSUE TITLE
群晖在目录内按照你写的启动容器代码无法运行。

### ISSUE THREAD

**Issue by shadowtyw** [mikumifa/QChatGPT-Docker-Installer#15]
4. 启动
i. 启动mirai容器
docker compose run -itd mirai
ii. 启动主程序容器
docker compose run -itd setup

以上两端代码无法创建docker运行，如下更改后可正常创建docker：

docker-compose  -f docker-compose.yaml up -d

其他系统我不知道，但是黑群晖是这样的。

如果已经安装了mirai，自行删除docker-compose.yaml内的以下代码即可单独安装qchatgpt：
  mirai:
    build:
      context: .
      dockerfile: _mirai.Dockerfile
    environment:
      LANG: "C.UTF-8"
    restart: always
    network_mode: host
    volumes:
    - ./mirai:/mirai

**Comment by mikumifa** [comment]
感谢反馈
