### ISSUE TITLE
ii. 在mirai上登录QQ   这步出现禁止登录

### ISSUE THREAD

**Issue by objdjm** [mikumifa/QChatGPT-Docker-Installer#16]
![Snipaste_2023-02-25_22-59-26](https://user-images.githubusercontent.com/120356556/221363943-2741f887-6c09-4734-8272-7f76e127b5fe.png)

**Comment by mikumifa** [comment]
这个问题目前原因位置，建议全部删除后重新安装。

**Comment by mikumifa** [comment]
[可以试试这个](https://github.com/mamoe/mirai/issues/2524)

**Comment by objdjm** [comment]
> [可以试试这个](https://github.com/mamoe/mirai/issues/2524)
改了协议还是不行

**Comment by mikumifa** [comment]
我知道，重新安装是绝对可以的，因为我以前就是这样修好的

**Comment by objdjm** [comment]
> 我知道，重新安装是绝对可以的，因为我以前就是这样修好的

刚才我协议没有把每个地方都改成MACOS。现在是登录成功了，可是输入两条启动命令好像没有任何反应
![image](https://user-images.githubusercontent.com/120356556/221369441-54f6a566-a837-466d-80af-4b92c133b560.png)

**Comment by mikumifa** [comment]
要配置自动登录，只要登录成功了应该就没问题了

**Comment by twwch** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/44161003/222041017-7f3b2157-f290-4f0a-8d19-facc8bc5e53e.png">
加上这个配置就可以了
