### ISSUE TITLE
为什么更新卡住了

### ISSUE THREAD

**Issue by shenmadouyaowen** [mikumifa/QChatGPT-Docker-Installer#18]
国外服务器：Ubuntu 20.04.5 LTS x86_64
已更新就卡在下面这个进度不走
![image](https://user-images.githubusercontent.com/12426724/221802346-10d2b9b3-5386-4b4e-b933-b6a161f25959.png)

![image](https://user-images.githubusercontent.com/12426724/221802258-f3c86116-172b-4890-ad63-6b857416450e.png)

**Comment by mikumifa** [comment]
你好，建议去原项目issue去看看，我这边只负责docker部署[此处](https://github.com/RockChinQ/QChatGPT)

**Comment by shenmadouyaowen** [comment]
好的,谢谢啦

**Comment by RockChinQ** [comment]
由于dulwich库解决储存库较慢，目前自动更新大概需要几个小时

**Comment by shenmadouyaowen** [comment]
> 由于dulwich库解决储存库较慢，目前自动更新大概需要几个小时

怪不得,已经手动更新了,谢谢
