### ISSUE TITLE
请求超时

### ISSUE THREAD

**Issue by mqEpiphany** [mikumifa/QChatGPT-Docker-Installer#22]
为什么现在和机器人对话一直提示请求超时?查看日志并没有发现错误.
![image](https://user-images.githubusercontent.com/79396680/222646070-1bcfa32f-902f-48f3-8b53-ea1dc2dc1147.png)

**Comment by mqEpiphany** [comment]
![image](https://user-images.githubusercontent.com/79396680/222646306-38a090b6-c3d6-40ed-a6e1-291e4968037a.png)

**Comment by mikumifa** [comment]
[原项目给的原因](https://github.com/RockChinQ/QChatGPT/issues/198),敏感时期

**Comment by mqEpiphany** [comment]
好的 十分感谢
