### ISSUE TITLE
qq号登陆了，怎么和chatgpt进行关联

### ISSUE THREAD

**Issue by yanpengfei-git** [mikumifa/QChatGPT-Docker-Installer#3]
qq号登陆了，怎么和chatgpt进行关联，在哪里配置账号密码

**Comment by mikumifa** [comment]
在bot目录下创建config.py，将config-template.py的内容复制进去，编辑config.py修改必需项，config.py填写api_key，和qq账号

**Comment by yanpengfei-git** [comment]
好的
