### ISSUE TITLE
启动主程序容器时报错ERROR: Service 'setup' failed to build

### ISSUE THREAD

**Issue by 3280777856** [mikumifa/QChatGPT-Docker-Installer#6]
执行docker-compose run -d setup时报错
![image](https://user-images.githubusercontent.com/86226854/214913671-10b6895a-7c3d-4f39-892e-dca0379db9ab.png)
![image](https://user-images.githubusercontent.com/86226854/214913843-30c21750-9ad9-44e1-9815-62af8b3e8d05.png)
config.py已经修改

**Comment by cherrieszzz** [comment]
如何解决的

**Comment by 3280777856** [comment]
@cherrieszzz docker安装的问题，请参考[此链接](https://blog.csdn.net/Hilaph/article/details/124295252)
